#!/usr/bin/env zsh

# Android
export ANDROID_HOME=/home/hakier/dev/tools/android-sdk-linux
export JAVA_HOME=$(update-alternatives --query javac | sed -n -e 's/Best: *\(.*\)\/bin\/javac/\1/p')
export PATH="${PATH}:${ANDROID_HOME}/tools"
