#!/usr/bin/env zsh

loadRC helpers

function repoInfo {
    repoRemote=`git remote -v | grep push | sed 's/.*\t\(.*\) .*/\1/'`
    repoHost=`echo ${repoRemote} | cut -d: -f1`
    repoPath=`echo ${repoRemote} | cut -d: -f2`

    echo -e "Host: ${repoHost}\nPath: ${repoPath}\n$(printLine)"
}

function remote {
    repoInfo

    ssh ${repoHost} "cd ${repoPath}; ${@}"
}

alias g=git
alias cdr='cd `git root`'
alias pc=proxychains
alias gp='pc git'
alias gf='git fetch'
alias cdr='cd $(git root)'
