#!/usr/bin/env zsh

loadRC helpers
loadRC git-remote
loadRC git-merge

alias g=git
alias cdr='cd `git root`'
alias pc=proxychains
alias gp='pc git'
alias gf='git fetch'
alias cdr='cd $(git root)'
alias gco='golem checkout'
alias gpob='git po `g brn`'

function gitAmendDate {
    date="${1}"
    [[ -z "${date}" ]] &&
        echo "usage: gitAmendDate 'Thu Apr 30 2020 08:13 CEST'" ||
        GIT_COMMITTER_DATE="${date}" git commit --amend --no-edit --date "${date}"
}

